spring:
  application:
    name: saga-product

  profiles:
    active: dev

  config:
    import: "optional:configserver:http://localhost:8881"

logging:
  level:
    com.ch.sagaproduct.consumer: debug
server:
  port: 9992
