spring:
  application:
    name: saga-product

  profiles:
    active: dev

  config:
    import: "optional:configserver:http://localhost:8881"

  # 업로드 설정
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    com.ch.sagaproduct: debug


